issuer: http://localhost:5556/dex

storage:
  type: memory

web:
  http: 0.0.0.0:5556
  allowedOrigins:
    - "*"

oauth2:
  responseTypes:
    - code
    - token
    - id_token
  skipApprovalScreen: true

staticClients:
  - id: terrakube-app
    name: Terrakube
    public: true
    redirectURIs:
      - http://localhost:3000
      - http://localhost:3000/login
      - /device/callback
      - http://localhost:10000/login
      - http://localhost:10001/login

enablePasswordDB: true

staticPasswords:
  - email: admin@terrakube.local
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W" # password
    username: admin
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
